version: '3.1'

services:
  postgis:
    image: postgis/postgis
    container_name: postgis
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wisoft.io
      PGADMIN_DEFAULT_PASSWORD: admin
    links:
      - postgis